set_property PACKAGE_PIN B1 [get_ports clkin_p]
set_property IOSTANDARD LVDS_25 [get_ports clkin_p]
set_property PACKAGE_PIN C2 [get_ports datain_p]
set_property IOSTANDARD LVDS_25 [get_ports clkout_p]
set_property IOSTANDARD LVDS_25 [get_ports dataout_p]
set_property PACKAGE_PIN E2 [get_ports clkout_p]
set_property PACKAGE_PIN G1 [get_ports dataout_p]
set_property PACKAGE_PIN E1 [get_ports rst]
set_property IOSTANDARD LVCMOS25 [get_ports rst]
set_property IOSTANDARD LVDS_25 [get_ports datain_p]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets system_i/artix_serdes_0/inst/clkin]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets system_i/artix_serdes_0/inst/clk]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets system_i/artix_serdes_0/inst/rst_reg_0]